### ISSUE TITLE
Glimpse for intellij?

### ISSUE THREAD

**Issue by arabshapt** [MarcoIeni/intelli-space#58]
I saw your new project "Glimpse" for vs code. Are you planning to create one for intellij as well? I like the "why"(your reasoning behind glimpse). Do you think it makes sense to shortcut sequences for intellij as well?
And I also have a question regarding uppercase letters that you use in the sequences... Generally uppercase letters are harder to type compared to lowercase, because they require holding or tapping shift key. E.g. lazygit uses uppercase keys for commands that are a more dangerous or could cause a negative effect(like git push). Do you try to do the same? I think often used commands should consist of lowercase letters... What do you think about it? I know that main point of these sequences is mnemonics and not necessarily speed, because speed will come over time, but still uppercase is extra effort compared to lowercase.

**Comment by marcoieni** [comment]
Hi!

> Are you planning to create one for intellij as well?

No, I don't have time for it, but you are the second person asking :)

> Do you think it makes sense to shortcut sequences for intellij as well?

- Yes because we can have key bindings that makes more sense for beginners
- No because I don't think intellij has a "scripting" language like javascript embedded, so you can't use the same [config](https://glimpse.ieni.dev/docs/configuration) style, right?

If you want to recreate glimpse for intellij, go for it :)

**Comment by marcoieni** [comment]
> Do you try to do the same?

Yes, I try to use lowecase for most used commands 👍 e.g. in glimpse `c` is for `configuration`, while `C` is for `comment`, because imo people uses configuration more than comments, but that's just my thought. It's difficult to get these things right, and you are going to disappoint many people. That's what configs are for :)
