### ISSUE TITLE
How do you remember all the keys? 

### ISSUE THREAD

**Issue by IanQS** [MarcoIeni/intelli-space#7]
In Spacemacs, pressing `<leader> X` leads to a small tooltip window popping up and showing you what keys you might be able to press and what they might do. Is there such a thing here? 

P.s do you know how this works (if at all) with KeyPromoterX? 

BTW, Thanks for the awesome job on this! Having 1 set of efficient keybindings across my editor was something I sorely missed when I moved away from Spacemacs (now using Clion, Pycharm and IntelliJ)

**Comment by marcoieni** [comment]
> How do you remember all the keys?

I don't, I use a subset of them.

> In Spacemacs, pressing <leader> X leads to a small tooltip window popping up and showing you what keys you might be able to press and what they might do. Is there such a thing here?

No, there isn't something like which-key, although I would really like to try to implement it. I played with kotlin, but I have never done IntelliJ plugin development before. Since it is a very requested feature, I opened issue #8.

You can press `SPC h k`, but that's not probably what you want.

> P.s do you know how this works (if at all) with KeyPromoterX?

I haven't tried KeyPromoterX. I don't know if it interacts with IdeaVim, but I don't think so.

> BTW, Thanks for the awesome job on this! Having 1 set of efficient keybindings across my editor was something I sorely missed when I moved away from Spacemacs (now using Clion, Pycharm and IntelliJ)

Thank you for submitting your feedback :)
